import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, User, Plus, ArrowLeft } from "lucide-react";
import { usePlayerSearch } from "@/hooks/usePlayerSearch";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useQueryClient } from "@tanstack/react-query";
import type { Player } from "@/types/admin";

interface PlayerSearchDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSelectPlayer: (player: Player) => void;
  csvPlayerName: string;
  genderFilter?: string;
}

export function PlayerSearchDialog({
  open,
  onOpenChange,
  onSelectPlayer,
  csvPlayerName,
  genderFilter,
}: PlayerSearchDialogProps) {
  const [searchTerm, setSearchTerm] = useState(csvPlayerName);
  const [showAddForm, setShowAddForm] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [newPlayerData, setNewPlayerData] = useState({
    name: "",
    country: "",
    gender: genderFilter || "male",
  });
  
  const { data: searchResults, isLoading } = usePlayerSearch(searchTerm, open, genderFilter);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const handleSelect = (result: any) => {
    const player: Player = {
      id: result.player_id || result.id,
      name: result.name,
      country: result.country || "",
      gender: result.gender || "",
      player_code: result.player_code || "",
      email: result.email || null,
      date_of_birth: result.date_of_birth || null,
      dupr_id: result.dupr_id || null,
    };
    onSelectPlayer(player);
    onOpenChange(false);
    setSearchTerm("");
    setShowAddForm(false);
  };

  const handleShowAddForm = () => {
    setNewPlayerData({
      name: searchTerm,
      country: "",
      gender: genderFilter || "male",
    });
    setShowAddForm(true);
  };

  const handleCreatePlayer = async () => {
    if (!newPlayerData.name.trim() || !newPlayerData.country.trim()) {
      toast({
        variant: "destructive",
        title: "Missing fields",
        description: "Name and country are required",
      });
      return;
    }

    setIsCreating(true);
    try {
      // player_code is auto-generated by database
      const insertData: { name: string; country: string; gender: string } = {
        name: newPlayerData.name.trim(),
        country: newPlayerData.country.trim(),
        gender: newPlayerData.gender,
      };
      
      const { data, error } = await supabase
        .from("players")
        .insert([insertData as any])
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Player created",
        description: `${data.name} has been added`,
      });

      // Invalidate player search cache
      queryClient.invalidateQueries({ queryKey: ["player-search"] });

      // Select the newly created player
      const player: Player = {
        id: data.id,
        name: data.name,
        country: data.country,
        gender: data.gender,
        player_code: data.player_code,
        email: data.email,
        date_of_birth: data.date_of_birth,
        dupr_id: data.dupr_id,
      };
      onSelectPlayer(player);
      onOpenChange(false);
      setSearchTerm("");
      setShowAddForm(false);
      setNewPlayerData({ name: "", country: "", gender: genderFilter || "male" });
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error.message || "Failed to create player",
      });
    } finally {
      setIsCreating(false);
    }
  };

  const handleClose = (open: boolean) => {
    if (!open) {
      setShowAddForm(false);
      setSearchTerm("");
    }
    onOpenChange(open);
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>
            {showAddForm ? "Add New Player" : "Search for Player"}
          </DialogTitle>
        </DialogHeader>

        {showAddForm ? (
          <div className="space-y-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowAddForm(false)}
              className="mb-2"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to search
            </Button>

            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="new-player-name">Name *</Label>
                <Input
                  id="new-player-name"
                  value={newPlayerData.name}
                  onChange={(e) => setNewPlayerData({ ...newPlayerData, name: e.target.value })}
                  placeholder="Enter player name"
                  autoFocus
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="new-player-country">Country *</Label>
                <Input
                  id="new-player-country"
                  value={newPlayerData.country}
                  onChange={(e) => setNewPlayerData({ ...newPlayerData, country: e.target.value })}
                  placeholder="Enter country"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="new-player-gender">Gender *</Label>
                <Select
                  value={newPlayerData.gender}
                  onValueChange={(value) => setNewPlayerData({ ...newPlayerData, gender: value })}
                  disabled={!!genderFilter}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="male">Male</SelectItem>
                    <SelectItem value="female">Female</SelectItem>
                  </SelectContent>
                </Select>
                {genderFilter && (
                  <p className="text-xs text-muted-foreground">
                    Gender is fixed based on the selected category
                  </p>
                )}
              </div>

              <Button
                onClick={handleCreatePlayer}
                disabled={isCreating || !newPlayerData.name.trim() || !newPlayerData.country.trim()}
                className="w-full"
              >
                {isCreating ? "Creating..." : "Create & Select Player"}
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search by name, code, or country..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
                autoFocus
              />
            </div>

            <ScrollArea className="h-[300px] border rounded-md">
              {isLoading ? (
                <div className="p-4 text-center text-muted-foreground">
                  Searching...
                </div>
              ) : searchResults && searchResults.length > 0 ? (
                <div className="divide-y">
                  {searchResults.map((result: any) => (
                    <div
                      key={result.player_id || result.id}
                      className="p-3 hover:bg-muted/50 transition-colors"
                    >
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center">
                            <User className="h-4 w-4 text-primary" />
                          </div>
                          <div>
                            <p className="font-medium">{result.name}</p>
                            <p className="text-sm text-muted-foreground">
                              {result.player_code || "No code"} • {result.country || "Unknown"}
                              {result.total_points && ` • ${result.total_points} pts`}
                            </p>
                          </div>
                        </div>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleSelect(result)}
                        >
                          Select
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : searchTerm.trim() ? (
                <div className="p-4 text-center space-y-4">
                  <p className="text-muted-foreground">
                    No players found matching "{searchTerm}"
                  </p>
                  <Button onClick={handleShowAddForm} variant="outline">
                    <Plus className="h-4 w-4 mr-2" />
                    Add New Player
                  </Button>
                </div>
              ) : (
                <div className="p-4 text-center text-muted-foreground">
                  Enter a search term to find players
                </div>
              )}
            </ScrollArea>

            {/* Always show add button at bottom */}
            <Button
              variant="ghost"
              size="sm"
              onClick={handleShowAddForm}
              className="w-full text-muted-foreground"
            >
              <Plus className="h-4 w-4 mr-2" />
              Can't find player? Add new
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
